name: Deploy website to GitHub Pages

env:
  WC_HUGO_VERSION: '0.123.3'

on:
  # Trigger the workflow every time you push to the `main` branch
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build website
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Fetch history for Hugo's .GitInfo and .Lastmod
          fetch-depth: 0
      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2.5.0
        with:
          hugo-version: ${{ env.WC_HUGO_VERSION }}
          extended: true
      - name: Create website
        env:
          HUGO_ENVIRONMENT: production
        run: |
          echo "Hugo Cache Dir: $(hugo config | grep cachedir)"
          hugo --minify
      - name: Zip website
        run: |
          zip -r website.zip public
      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: website
          path: "./website.zip"
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
